-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 18:15:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE restaurant_equipment_sales_system;

-- -----------------------------------------------------
-- Table CATEGORIES
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS CATEGORIES (
  ca_id INT NOT NULL AUTO_INCREMENT,
  CategoryName VARCHAR(20) NOT NULL,
  PRIMARY KEY(ca_id));


-- -----------------------------------------------------
-- Table PRODUCTS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS PRODUCTS (
  pro_id INT NOT NULL AUTO_INCREMENT,
  CATEGORIES_ca_id INT NOT NULL,
  pro_Name VARCHAR(20) NOT NULL,
  pro_Price FLOAT NOT NULL,
  Description MEDIUMTEXT NULL,
  PRIMARY KEY (pro_id, CATEGORIES_ca_id),
  FOREIGN KEY (CATEGORIES_ca_id) REFERENCES CATEGORIES(ca_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table CUSTOMERS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS CUSTOMERS (
  c_id INT NOT NULL AUTO_INCREMENT,
  c_name VARCHAR(20) NOT NULL DEFAULT 'no name',
  c_email VARCHAR(20) NOT NULL UNIQUE,
  c_phone VARCHAR(11) NOT NULL UNIQUE,
  c_address VARCHAR(50) NOT NULL,
  PRIMARY KEY (c_id));


-- -----------------------------------------------------
-- Table ORDERS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS ORDERS (
  o_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  CUSTOMERS_c_id INT NOT NULL,
  o_date TIMESTAMP(5) NOT NULL,
  QTY INT NOT NULL DEFAULT 1,
  FOREIGN KEY (CUSTOMERS_c_id) REFERENCES CUSTOMERS(c_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table PAYMENT
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS PAYMENT (
  p_id INT NOT NULL AUTO_INCREMENT,
  ORDERS_o_id INT NOT NULL,
  p_date DATETIME(5) NOT NULL,
  p_amount FLOAT NOT NULL,
  p_method VARCHAR(40) NOT NULL UNIQUE,
  PRIMARY KEY (p_id, ORDERS_o_id),
  FOREIGN KEY (ORDERS_o_id) REFERENCES ORDERS (o_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table SUPPLIER
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS SUPPLIER (
  s_id INT NOT NULL AUTO_INCREMENT,
  s_name VARCHAR(50) NOT NULL,
  s_address VARCHAR(50) NOT NULL,
  s_phone VARCHAR(11) NOT NULL UNIQUE,
  s_email VARCHAR(20) NOT NULL UNIQUE,
  PRIMARY KEY (s_id));


-- -----------------------------------------------------
-- Table PRODUCT_SUPPLIER_
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS PRODUCT_SUPPLIER_ (
  prod_supl_id INT NOT NULL AUTO_INCREMENT,
  PRODUCTS_pro_id INT NOT NULL,
  SUPPLIER_s_id INT NOT NULL,
  PRIMARY KEY (prod_supl_id, PRODUCTS_pro_id, SUPPLIER_s_id),
  FOREIGN KEY (PRODUCTS_pro_id) REFERENCES PRODUCTS (pro_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY (SUPPLIER_s_id) REFERENCES SUPPLIER (s_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table ROLES
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS ROLES (
  r_id INT NOT NULL AUTO_INCREMENT,
  r_Name ENUM('user', 'customer', 'manager') NOT NULL DEFAULT 'user',
  PRIMARY KEY (r_id));


-- -----------------------------------------------------
-- Table USERS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS USERS (
  u_id INT NOT NULL AUTO_INCREMENT,
  ROLES_r_id INT NOT NULL,
  u_UserName VARCHAR(30) UNIQUE NOT NULL,
  u_Password VARCHAR(15) UNIQUE NOT NULL,
  u_Email VARCHAR(20) UNIQUE NOT NULL,
  PRIMARY KEY (u_id, ROLES_r_id),
  FOREIGN KEY (ROLES_r_id) REFERENCES ROLES (r_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table INVOICES
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS INVOICES (
  i_id INT NOT NULL AUTO_INCREMENT,
  ORDERS_o_id INT NOT NULL,
  i_date TIMESTAMP(5) NOT NULL,
  i_totalAmount FLOAT NOT NULL,
  PRIMARY KEY (i_id, ORDERS_o_id),
  FOREIGN KEY (ORDERS_o_id) REFERENCES ORDERS (o_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table INVENTORY
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS INVENTORY (
  in_id INT NOT NULL AUTO_INCREMENT,
  PRODUCTS_pro_id INT NOT NULL,
  QuantityInStock INT NOT NULL,
  PRIMARY KEY (in_id, PRODUCTS_pro_id),
  FOREIGN KEY (PRODUCTS_pro_id) REFERENCES PRODUCTS (pro_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table SHIPPING
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS SHIPPING (
  sh_id INT NOT NULL AUTO_INCREMENT,
  ORDERS_o_id INT NOT NULL,
  sh_address VARCHAR(50) NOT NULL,
  sh_date DATE NOT NULL,
  PRIMARY KEY (sh_id, ORDERS_o_id),
  FOREIGN KEY (ORDERS_o_id) REFERENCES ORDERS (o_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table REVIEWS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS REVIEWS (
  re_id INT NOT NULL AUTO_INCREMENT,
  PRODUCTS_pro_id INT NOT NULL,
  CUSTOMERS_c_id INT NOT NULL,
  re_rating FLOAT(2,1) NULL,
  re_comment MEDIUMTEXT NULL,
  PRIMARY KEY (re_id, PRODUCTS_pro_id, CUSTOMERS_c_id),
  FOREIGN KEY (PRODUCTS_pro_id) REFERENCES PRODUCTS (pro_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY (CUSTOMERS_c_id) REFERENCES CUSTOMERS (c_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table REPORTS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS REPORTS (
  re_id INT NOT NULL AUTO_INCREMENT,
  USERS_u_id INT NOT NULL,
  re_Content MEDIUMTEXT NOT NULL,
  re_CreatedDate TIMESTAMP(5) NOT NULL,
  PRIMARY KEY (re_id, USERS_u_id),
  FOREIGN KEY (USERS_u_id) REFERENCES USERS (u_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table ORDER_ITEM
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS ORDER_ITEM (
  orders_item_id INT NOT NULL AUTO_INCREMENT,
  PRODUCTS_pro_id INT NOT NULL,
  ORDERS_o_id INT NOT NULL,
  QTY INT NOT NULL DEFAULT 1,
  PRIMARY KEY (orders_item_id, PRODUCTS_pro_id, ORDERS_o_id),
  FOREIGN KEY (PRODUCTS_pro_id) REFERENCES PRODUCTS (pro_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY (ORDERS_o_id) REFERENCES ORDERS (o_id)
  ON DELETE CASCADE
  ON UPDATE CASCADE);
